### ISSUE TITLE
Trying to run Mycroft on RPI 2 model B - with debian bullseye

### ISSUE THREAD

**Issue by berndverhofstadt** [MichaIng/DietPi-Docs#647]
Hi,
After a clean installation of the latest dietpi (bullseye) release, I was able to install the dietpi-software _Mycroft AI_. When I try to launch `mycroft-cli-client`, the following error is thrown. Any idea what can caused this? I've followed the [instructions](https://dietpi.com/docs/software/hardware_projects/#mycroft-ai)

```
root@DietPi2:~# mycroft-cli-client


Traceback (most recent call last):
  File "/mnt/dietpi_userdata/mycroft-core/mycroft/identity/__init__.py", line 55, in load
    identity_lock.acquire()
  File "/mnt/dietpi_userdata/mycroft-core/mycroft/util/combo_lock.py", line 59, in acquire
    self.plock.acquire()
  File "/mnt/dietpi_userdata/mycroft-core/.venv/lib/python3.9/site-packages/fasteners/process_lock.py", line 151, in acquire
    self._do_open()
  File "/mnt/dietpi_userdata/mycroft-core/.venv/lib/python3.9/site-packages/fasteners/process_lock.py", line 123, in _do_open
    self.lockfile = open(self.path, 'a')
PermissionError: [Errno 13] Permission denied: '/tmp/identity-lock'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/mnt/dietpi_userdata/mycroft-core/mycroft/client/text/__main__.py", line 71, in <module>
    main()
  File "/mnt/dietpi_userdata/mycroft-core/mycroft/client/text/__main__.py", line 44, in main
    config = Configuration.get()
  File "/mnt/dietpi_userdata/mycroft-core/mycroft/configuration/config.py", line 219, in get
    return Configuration.load_config_stack(configs, cache, remote)
  File "/mnt/dietpi_userdata/mycroft-core/mycroft/configuration/config.py", line 255, in load_config_stack
    configs.append(RemoteConf())
  File "/mnt/dietpi_userdata/mycroft-core/mycroft/configuration/config.py", line 146, in __init__
    if not is_paired():
  File "/mnt/dietpi_userdata/mycroft-core/mycroft/api/__init__.py", line 498, in is_paired
    api = DeviceApi()
  File "/mnt/dietpi_userdata/mycroft-core/mycroft/api/__init__.py", line 223, in __init__
    super(DeviceApi, self).__init__("device")
  File "/mnt/dietpi_userdata/mycroft-core/mycroft/api/__init__.py", line 56, in __init__
    self.identity = IdentityManager.get()
  File "/mnt/dietpi_userdata/mycroft-core/mycroft/identity/__init__.py", line 101, in get
    IdentityManager.load()
  File "/mnt/dietpi_userdata/mycroft-core/mycroft/identity/__init__.py", line 59, in load
    identity_lock.release()
  File "/mnt/dietpi_userdata/mycroft-core/mycroft/util/combo_lock.py", line 64, in release
    self.plock.release()
  File "/mnt/dietpi_userdata/mycroft-core/.venv/lib/python3.9/site-packages/fasteners/process_lock.py", line 180, in release
    raise threading.ThreadError("Unable to release an unacquired"
RuntimeError: Unable to release an unacquired lock
```
Thanks!
Bernd

**Comment by MichaIng** [comment]
Many thanks for your report.

Please try:
```
sudo -u mycroft mycroft-cli-client
```
